###
# GET HELLO WORLD

GET http://localhost:3000/

###
# POST SIGNUP

POST http://localhost:3000/api/users/register
accept: application/json
content-type: application/json

{
  "username": "haider",
  "email" : "haide7@gmail.com",
  "password": "My_password1",
  "role": "user"
}

###
# POST LOGIN 

POST http://localhost:3000/api/users/login
accept: application/json
content-type: application/json

{
  "email" : "haide7@gmail.com",
  "password": "My_password1"
}
